### ISSUE TITLE
Navigation to the raw *.md file from the card

### ISSUE THREAD

**Issue by mikepharesjr** [samgiz/vscode-kanbn#17]

**Comment by samgiz** [comment]
Hi, I agree this could be useful, though it's not a priority of mine at the moment. Would you like to just have a button in the task editor / board panel, or would you expect this to be a command in the command pallette?

**Comment by mikepharesjr** [comment]
I was able to stumble through updating the code to add a button next the delete button in edit mode.

          // Go to raw task and close the webview panel
          case "kanbn.goToRaw":
            KanbnTaskPanel.panels[message.panelUuid].dispose();
            delete KanbnTaskPanel.panels[message.panelUuid];
            let uri = Uri.file(join(this._workspacePath, ".kanbn", "tasks", message.taskId + ".md"));
            await commands.executeCommand('vscode.open', uri);
            return;

**Comment by samgiz** [comment]
Glad to hear that! I'm happy to add it to the extension if you make a pull request :)
