### ISSUE TITLE
Publish on Open-VSX

### ISSUE THREAD

**Issue by jay7x** [samgiz/vscode-kanbn#22]
Any chance to get this extension published in the https://open-vsx.org registry? This would be great for VSCodium users :)

**Comment by samgiz** [comment]
I'll see if I can get this set up.

**Comment by samgiz** [comment]
It has now been published: https://open-vsx.org/extension/samgiz/vscode-kanbn-boards.

**Comment by jay7x** [comment]
Thank you!
